localProxies:
    postgres:
        proxyAddress: '0.0.0.0:6543'
        connectingAddress: '127.0.0.1:5432'
    google:
        proxyAddress: '0.0.0.0:4000'
        connectingAddress: 'google.com:80'
    redis:
        proxyAddress: '0.0.0.0:6380'
        connectingAddress: '127.0.0.1:6379'
